### ISSUE TITLE
用vlc播放easydarwin实时流，前几秒都是花屏

### ISSUE THREAD

**Issue by yiyinkuang** [EasyDarwin/EasyDarwin#10]
用ffmpeg 采集，编码264或者265，推送到easydarwin，（指令：ffmpeg -f dshow -i video="HD UVC WebCam" -r 25 -s 640x480 -vcodec libx265 -preset:v ultrafast -tune:v zerolatency -rtsp_transport tcp -f rtsp rtsp://120.26.113.79/live.sdp）
，，然后客户端vlc播放实时视频，，前几秒都是花屏，，，

**Comment by xiejiashu** [comment]
这个问题有两种处理方式：

**Comment by yiyinkuang** [comment]
哪两种？？

**Comment by xiejiashu** [comment]
1、播放器端优化，需要将花屏帧过滤掉，也就是拿到关键帧才开始播放；
2、服务端优化，保证第一帧发送关键帧给客户端；
这个问题服务端后面会优化的

**Comment by yiyinkuang** [comment]
嗯，，服务器转发的时候是实时转发吗？？还是先缓存，，ffmpeg推送第一帧数据应该是i帧吧，，tcp是可以保证顺序的啊。。。

**Comment by xiejiashu** [comment]
有缓冲，但是到一定时间后就会释放，可以配置，具体参考：http://www.easydarwin.org/article/doc/EasyDarwin/35.html#6

**Comment by yiyinkuang** [comment]
我配置成0，，前几秒还是会有花屏

**Comment by xiejiashu** [comment]
别着急，上面说到的两个办法，我都会处理的

**Comment by gentleboy** [comment]
请问前几秒花屏的这个问题，服务端优化了没？我前两天用vlc播放摄像头的rtsp流，前几秒还是会花屏。另外，如果我想在播放器端优化的话，应该设置vlc的哪个参数呢？

**Comment by xiejiashu** [comment]
我们最近实现了关键帧推送的功能，具体说明看一下：http://blog.csdn.net/xiejiashu/article/details/51106371，不过方案还没有完全完善，还需要一些时间

**Comment by xiejiashu** [comment]
最新版本已经初步实现了关键帧缓冲的功能，可以继续测试看看
