### ISSUE TITLE
Android pusher stream is available to all user accounts

### ISSUE THREAD

**Issue by kirantpatil** [EasyDarwin/EasyDarwin#101]
Hi,

1. Locally I installed EasyDarwin server
2. Apart from admin user, I created other users
3. Installed Easypusher android app and pushed stream to server
4. I login as admin and I could see the connection at Pusher page, http://192.168.0.121:10008/#/pushers/1
5. I logged in as kiran user and I could see the connection as well 

How to restrict stream to only single user of the EasyDarwin server ?

Thanks.

**Comment by kirantpatil** [comment]
EasyRTSP client uses below way.

void PrintUsage()
{
	printf("Usage:\n");
	printf("------------------------------------------------------\n");
	printf("%s [-d <host> -p <port> -n <streamName> -u <RTSPURL>]\n", ProgName);
	printf("Help Mode:   %s -h \n", ProgName );
	printf("For example: %s -d 115.29.139.20 -p 554 -n easypusher_rtsp.sdp -u rtsp://admin:admin@anfengde.f3322.org/22\n", ProgName); 
	printf("------------------------------------------------------\n");
}

I tried to provide the, admin:admin@192.168.0.34 as "IP" and "554" as port and "pstream" as stream name in Android Easypusher app, but it is not working at all. 

It works when I remove "admin:admin@" and keep just 192.168.0.34.

Please find the attached image.

![android_easypusher](https://user-images.githubusercontent.com/1178055/46403962-88563780-c721-11e8-96d2-090d12ff7898.jpg)

**Comment by zhanjx1314** [comment]
你可以自己实现握手的过程。我做过根据流名称进行验证。

发自我的 iPhone

在 2018年10月3日，下午6:04，kirantpatil <notifications@github.com<mailto:notifications@github.com>> 写道：


EasyRTSP client uses below way.

void PrintUsage()
{
printf("Usage:\n");
printf("------------------------------------------------------\n");
printf("%s [-d -p -n -u ]\n", ProgName);
printf("Help Mode: %s -h \n", ProgName );
printf("For example: %s -d 115.29.139.20 -p 554 -n easypusher_rtsp.sdp -u rtsp://admin:admin@anfengde.f3322.org<mailto:admin@anfengde.f3322.org>/22\n", ProgName);
printf("------------------------------------------------------\n");
}

I tried to provide the, admin:admin@192.168.0.34<mailto:admin@192.168.0.34> as "IP" and "554" as port and "pstream" as stream name in Android Easypusher app, but it is not working at all.

It works when I remove "admin:admin@" and keep just 192.168.0.34.

Please find the attached image.

[android_easypusher]<https://user-images.githubusercontent.com/1178055/46403962-88563780-c721-11e8-96d2-090d12ff7898.jpg>

**Comment by kirantpatil** [comment]
Hi @zhanjx1314,

I am newbie to protocol coding, please post your code here as snippet for better understanding, provided you intend to make your code opensource/freesoftware.

Thanks.

**Comment by kirantpatil** [comment]
Hi @zhanjx1314,

How and where to implement validation based on username and password ?

Could you please share your code ?

Thanks.

**Comment by kirantpatil** [comment]
Hi @penggy ,

Please add authentication at the server that incoming stream with username and password is directed to the specific user account.

Ex:

ffmpeg -re -i C:\Users\Administrator\Videos\test.mkv -rtsp_transport tcp -vcodec h264 -f rtsp rtsp://**username:password**@localhost/test

**Comment by milkywayriver** [comment]
added.
set authorization_enable to 1
```
; 是否使能向服务器推流或者从服务器播放时验证用户名密码. [注意] 因为服务器端并不保存明文密码，所以推送或者播放时，客户端应该输入密码的md5后的值。
; password should be the hex of md5(original password)
authorization_enable=0
```
