### ISSUE TITLE
性能指标

### ISSUE THREAD

**Issue by ai4581532** [EasyDarwin/EasyDarwin#103]
请问下easydarwin有没有做相关性能测试，比如说最大支持多少并发，我这边调试并发超过50路流就容易报错

**Comment by milkywayriver** [comment]
> 请问下easydarwin有没有做相关性能测试，比如说最大支持多少并发，我这边调试并发超过50路流就容易报错

本机推流测试,并发1000路测试过. 除了资源占用高一些外并没有出现报错现象.请将你的错误信息发下.
