### ISSUE TITLE
easydarwin: not found

### ISSUE THREAD

**Issue by kirantpatil** [EasyDarwin/EasyDarwin#104]
Hi @penggy 

Linux installation is showing below error.

:~/Documents/home_automation/software/EasyDarwin$ sh start.sh 
start.sh: 3: start.sh: /home/smitha/Documents/software/EasyDarwin/easydarwin: not found
start.sh: 4: start.sh: /home/smitha/Documents/software/EasyDarwin/easydarwin: not found

Thanks.

**Comment by penggy** [comment]
npm run build:lin after clone source code on Linux.
Or download release version.
