### ISSUE TITLE
[FAQ] Why EasyDarwin ported Go from Nodejs ?

### ISSUE THREAD

**Issue by kirantpatil** [EasyDarwin/EasyDarwin#105]
@penggy,

I would like to know why was there a need to port code from Node.js to Go ?

Is it production ready or used in real world by anyone ?

Will there be any updates for security issues which I opened (providing authentication  username:password with URL, when client pushes stream to EasyDarwin) earlier ?

Will you provide the stream storage functionality in EasyDarwin, when a mobile access the stream from the server ?

Thanks.

**Comment by penggy** [comment]
Go build output easy to deploy, and works fine.
RTSP server authentication currently not support. Maybe support in the future, I can't give you an exact time.
Record push stream with ffmpeg is in processing.

**Comment by kirantpatil** [comment]
Great and thanks for update.
