### ISSUE TITLE
[Feature Request] Support for RTP end point

### ISSUE THREAD

**Issue by kirantpatil** [EasyDarwin/EasyDarwin#106]
Hi,

Can we push RTP stream only to EasyDarwin instead of using RTSP ?

Thanks.

**Comment by LinChengChun** [comment]
Maybe it is not support.It need a standard RTSP protocol streams.

发自我的 iPhone

**Comment by kirantpatil** [comment]
I am testing with CC3200 module which comes with RTSP protocol and works locally to send video and audio stream but not to cloud.

For which I am planning to skip all RTSP part and use only RTP to stream data(audio/video) directly to the cloud end point from my house.

That is the reason I am asking for only RTP endpoint for streaming my home to Easydarwin.

Thanks.

**Comment by milkywayriver** [comment]
I think the server need some RTSP dialog to get the endpoint's information. like the sdp, or "stream id" to deliver. for that reason, i think RTP streaming should not working

**Comment by kirantpatil** [comment]
Yes, that is the reason I changed FAQ to Feature Request. How hard it is
going to support for RTP end point.?

**Comment by milkywayriver** [comment]
This is actually not a technical reason. It is about the application needs. For example, how to assign an ID to your stream, and what URL to use for distribution. This problem is suitable for custom development. You can develop it yourself, there is no technical difficulty.

**Comment by kirantpatil** [comment]
Thanks @milkywayriver, I will look in to it.

**Comment by kirantpatil** [comment]
Wowza does support it.

https://www.wowza.com/docs/how-to-set-up-live-streaming-using-a-native-rtp-encoder-with-sdp-file

**Comment by milkywayriver** [comment]
@kirantpatil 
`
Note: Native RTP encoders deliver streams to Wowza Streaming Engine using the Real-time Transport Protocol (RTP). This protocol is used to deliver media streams to the server but doesn't have the capability to also deliver the session description information that the server requires to process the streams. This information is typically generated by the native RTP encoder and saved to a Session Description Protocol file (a file with a .sdp file name extension) that you must upload to the Wowza Streaming Engine server.`

from the doc,you need the sdp uploaded before streaming the rtp data. so, how to upload the sdp?
why not just use the rtsp protocol since it already done two thing?

**Comment by kirantpatil** [comment]
@milkywayriver 

Yes Sir, initially I planned to go for rtsp but by default we cannot make RTSP to push stream, instead it waits for initial setup to be initiated from client which I don't want. I would like to export the stream to public server as soon as the TI module starts. 

I am skipping the initial RTSP protocol details and trying to start the RTP directly, so that RTP doesn't need any session and it starts pushing stream to the configured SERVER IP (Wowza) directly.

Thanks for your concern.

**Comment by milkywayriver** [comment]
@kirantpatil 
It is possible to create an sdp file and push rtp to it. But how do you match the two on the server side? As far as I know, the rtp protocol does not contain information about its sdp.
Imagine that the server receives a separate piece of RTP data, how do you know which sdp it belongs to?

**Comment by kirantpatil** [comment]
@milkywayriver,
Yes, I am investigating that. I have raised the same question at the wowza community.
I am waiting for there reply.
Thanks.

**Comment by kirantpatil** [comment]
@milkywayriver, I would like to try another approach which is using Eashypusher.

I need to port Easypusher code to FreeRTOS.

May I know if it done by someone in the community else how to proceed ?

Thanks.
