### ISSUE TITLE
拉流分发

### ISSUE THREAD

**Issue by SmallShrimp** [EasyDarwin/EasyDarwin#107]
拉流分发功能不能用一直提示
![922](https://user-images.githubusercontent.com/8120385/49562871-526b4480-f958-11e8-8fa3-1c0397be13ea.png)

应该授权是没有问题的，通过FFmpeg工具拉流是没有问题的

**Comment by jiaozebo** [comment]
本地未能重现，需要更多日志。

**Comment by 18603769559** [comment]
项目组成员说可能是授权问题，正在解决。我也在关注这个问题。

**Comment by milkywayriver** [comment]
fixed. 
[https://github.com/EasyDarwin/EasyDarwin/commit/51f27c769d1fdd827e95b333ade11ac4eb2e224f](url)
