### ISSUE TITLE
拉流分发遇到问题

### ISSUE THREAD

**Issue by yarafa** [EasyDarwin/EasyDarwin#109]
遇到两个错，由于无法上传图片，就直接贴错误信息了。

1. Pull stream err : sdp : strconv.Atoi: parsing \"90000\": invalid syntax on line 9 'a=rtpmap:96 H264/90000
2. Pull stream err: Response StatusCode is 454

第二个错和一位兄弟之前提的应该是同一类问题。

另外，rtsp路径应该是没有问题的，也不是授权问题，因为用vlc或ffmpeg可以直接播放，也可以推流。

**Comment by milkywayriver** [comment]
你好！这两个问题已经解决。请更新后再试

**Comment by bcw104** [comment]
@milkywayriver 你好，“Pull stream err: Response StatusCode is 454” 这个问题确定解决了吗，我这边 clone 的最新代码运行下来还是报这个错误
