### ISSUE TITLE
建议添加拉流分发和停止拉流的接口

### ISSUE THREAD

**Issue by yarafa** [EasyDarwin/EasyDarwin#110]
如题，建议实现这两个接口，批量的。
另外，在web管理界面建议添加停止拉流的功能。

**Comment by milkywayriver** [comment]
有单独的拉流分发接口。没有批量的。
有停止拉流的功能。
![image](https://user-images.githubusercontent.com/4143638/50041522-3a4ea000-0091-11e9-9199-841b08ade3c8.png)
![image](https://user-images.githubusercontent.com/4143638/50041524-476b8f00-0091-11e9-933f-897e15ec20ab.png)
