### ISSUE TITLE
以udp方式推流rtsp失败

### ISSUE THREAD

**Issue by fmdsm** [EasyDarwin/EasyDarwin#112]
版本：EasyDarwin-windows-8.1.0-1811292235
使用了ffmpeg进行h264推流，默认udp的方式会超时，然后失败。使用tcp的方式能推流成功。
log显示[EasyDarwin] 2019/01/01 22:47:23 session[pusher][UDP][/test][CHsFESUiR] read tcp 192.168.199.100:554->192.168.199.100:1140: i/o timeout，而实际上我是用udp推流的。

**Comment by milkywayriver** [comment]
我们用ffmpeg 推流没有发现这个问题（UDP模式）
请再测下，把日志文件发下

**Comment by milkywayriver** [comment]
> 版本：EasyDarwin-windows-8.1.0-1811292235
> 使用了ffmpeg进行h264推流，默认udp的方式会超时，然后失败。使用tcp的方式能推流成功。
> log显示[EasyDarwin] 2019/01/01 22:47:23 session[pusher][UDP][/test][CHsFESUiR] read tcp 192.168.199.100:554->192.168.199.100:1140: i/o timeout，而实际上我是用udp推流的。

我们用ffmpeg 推流没有发现这个问题（UDP模式）
请再测下，把日志文件发下

**Comment by milkywayriver** [comment]
请使用最新版本验证，或者提供更多日志

**Comment by wangzhihui22** [comment]
同样遇到这个问题，udp推流失败，tcp成功。
采用win10部署服务，然后在系统防火墙打开554的udp端口，同一局域网下另一台电脑推流失败。
同样在系统防火墙打开554的tcp端口，使用tcp推流成功。
