### ISSUE TITLE
添加拉流Pull stream err: Response StatusCode is 401

### ISSUE THREAD

**Issue by hoshn** [EasyDarwin/EasyDarwin#114]
### 添加拉流提交后，提示：Pull stream err: Response StatusCode is 401，vlc可以播放rtsp流。格式类似：rtsp://admin:111222@192.168.1.17:554/Streaming/Channels/101

**Comment by milkywayriver** [comment]
这个问题应该已经修复过。请使用最新版本。或者提供更多日志
