### ISSUE TITLE
EasyDarwin-7.05版本中的web 页面 404 not found

### ISSUE THREAD

**Issue by EASYTAKEME** [EasyDarwin/EasyDarwin#116]

**Comment by ibanezsc** [comment]
需要配置nginx，以及重定向

**Comment by milkywayriver** [comment]
请使用go版本

**Comment by penglonghua** [comment]
如果是从golang ide 处运行，输出 http://xx.xx.xx.xx:10008 ,  浏览器打开  404 ,可以 配置 Output directory 为当前项目目录. 

>https://blog.csdn.net/binary2014/article/details/104054903
