### ISSUE TITLE
当realm字段里有空格时（HK部分相机）RTSP认证会失败，建议代码做如下修改。

### ISSUE THREAD

**Issue by songlei150** [EasyDarwin/EasyDarwin#117]
HK部分相机401反馈如下：
Digest realm="IP Camera(C3138)", nonce="742a0bfc8796112b4138121a85fbd29b", stale="FALSE"
[问题原因]
rstp/rtsp-client.go 
...
func DigestAuth(authLine string, method string, URL string) (string, error) {
...
		realmRex := regexp.MustCompile(`realm="(\S+)"`)
		result1 := realmRex.FindStringSubmatch(authLine)
...
}
正则表达式写的有问题
[做如下修改]
rstp/rtsp-client.go 
...
func DigestAuth(authLine string, method string, URL string) (string, error) {
...

	/*
		realm := ""
		nonce := ""
		realmRex := regexp.MustCompile(`realm="(\S+)"`)
		result1 := realmRex.FindStringSubmatch(authLine)

		nonceRex := regexp.MustCompile(`nonce="(\S+)"`)
		result2 := nonceRex.FindStringSubmatch(authLine)

		if len(result1) == 2 {
			realm = result1[1]
		} else {
			return "", fmt.Errorf("auth error : no realm found")
		}
		if len(result2) == 2 {
			nonce = result2[1]
		} else {
			return "", fmt.Errorf("auth error : no nonce found")
		}
	*/
	parseHeaderValue := func(header string, name string) string {
		index := strings.Index(header, name)
		if index == -1 {
			return ""
		}
		start := 1 + index + strings.Index(header[index:], `"`)
		end := start + strings.Index(header[start:], `"`)
		return strings.TrimSpace(header[start:end])
	}

	realm := parseHeaderValue(authLine, "realm")
	nonce := parseHeaderValue(authLine, "nonce")
...
}

**Comment by milkywayriver** [comment]
已改。
