### ISSUE TITLE
一个可能引起panic的Bug

### ISSUE THREAD

**Issue by songlei150** [EasyDarwin/EasyDarwin#118]
[代码位置]
routers/sys.go
func init {
...
pusherData = append(pusherData, CountData{Time: now, Total: uint(rtsp.Instance.GetPusherSize())})
...
}
此处在routers.init被系统运行时库调用时创建了go程定时执行获取转发信息，rtsp.Instance的初始化动作在main()调用后才执行，有可能在go程调用rtsp.Instance时在main()中还没有初始化好rtsp.Instance从而引起panic（例如，从main开始断点逐行调试代码时极大的会出现panic问题）。

**Comment by milkywayriver** [comment]
fixed
