### ISSUE TITLE
Rtsp Url没有path且不设置自定义Path,pusher管理存在bug

### ISSUE THREAD

**Issue by songlei150** [EasyDarwin/EasyDarwin#119]
[代码位置]
rtsp/rtsp-server.go
.....
func (server *Server) AddPusher(pusher *Pusher) {
...
	if _, ok := server.pushers[pusher.Path()]; !ok {
		server.pushers[pusher.Path()] = pusher
		go pusher.Start()
		logger.Printf("%v start, now pusher size[%d]", pusher, len(server.pushers))
		added = true
	}
...
}
....
Rtsp Url没有path且不设置自定义Path,此时Path为空，在pusher管理表中就会形成一个空字符串的Key，从而导致Rtsp Url没有path且不设置自定义Path的相机永远只能添加一个了。

**Comment by milkywayriver** [comment]
这种情况就需要客户端添加自定义path，其目的就是用来去重。

**Comment by songlei150** [comment]
@milkywayriver 
建议前端还是加个校验，在pusher管理表里产生一个空字符串的Key总感觉很奇怪。
