### ISSUE TITLE
对被测系统EasyDarwin压力测试，被测系统服务异常退出。

### ISSUE THREAD

**Issue by DuKune** [EasyDarwin/EasyDarwin#12]
1.测试环境：
硬件：
Intel(R) Xeon(R) CPU  E5430  @ 2.66GHz 2处理器 2 核心
内存：4G
软件：
操作系统：
CentOS release 6.4 (Final)
Kernel: 2.6.32-358.el6.x86_64

服务以调试模式启动：easydarwin -c ../WinNTSupport/easydarwin.xml -d

场景：
模拟2个user对被测系统循环发送rtsp请求，大概在2-3分钟时间左右，被测系统服务异常退出。

```日志：
#S->C:
#time: ms=336434 date=Thu, 26 Nov 2015 05:38:03 GMT
RTSP/1.0 200 OK\r\n
Server: EasyDarwin/7.0.2 (Build/15.1006; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 6\r\n
Session: 9089926291062351291\r\n
Range: npt=0.00000-30.04500\r\n
RTP-Info: url=rtsp://192.168.1.100:554/bs30smuxed.mp4/trackID=65536;seq=10103;rtptime=1628845141,url=rtsp://192.168.1.100:554/bs30smuxed.mp4/trackID=65537;seq=56254;rtptime=1105339346\r\n
段错误 (core dumped)```

注：模拟1个user对被测系统循环发送rtsp请求，运行20分钟，被测系统正常响应请求，无异常。

**Comment by DuKune** [comment]
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 11 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 10 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 8 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 8 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 7 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 6 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 5 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 4 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 3 3 - - - 
192.168.1.111 2015-11-26 08:45:15 192.168.1.100:554 /bs30smuxed.mp4 3 0 1 200 192.168.1.111 - - LibVLC/2.2.1%20(LIVE555%20Streaming%20Media%20v2014.07.25) - - - 30 0 0 RTP UDP mpeg4-generic/44100/2 MP4V-ES/90000 4607 0 4607 5 0 0 1 3 100 192.168.1.100 192.168.1.100 3 3 - - - 

这个是EasyDarwin.log日志

**Comment by xiejiashu** [comment]
已经fix，之前是因为对ReflectorSession错误引用导致的，请帮忙继续测试，谢谢！^-^
