### ISSUE TITLE
rtsp tcp 推流无音频流时，存在一个代码逻辑Bug

### ISSUE THREAD

**Issue by songlei150** [EasyDarwin/EasyDarwin#124]
**当RTSP TCP 纯视频推流时，RTPPack.Type成员被错误的设置成了RTP_TYPE_AUDIO。**
详细原因：
./rtsp/rtsp-session.go

type Session struct {
...
	//tcp channels
	aRTPChannel        int
	aRTPControlChannel int
	vRTPChannel        int
	vRTPControlChannel int
...
}
**Session 结构vRTPChannel/vRTPControlChannel/aRTPChannel/aRTPControlChannel成员变量，初始化使用了默认的0。当rtsp tcp 推流时，推流端会发起SETUP协商interleaved字段,如下代码：**
./rtsp/rtsp-session.go
...
func (session *Session) handleRequest(req *Request) {
...
		if tcpMatchs := mtcp.FindStringSubmatch(ts); tcpMatchs != nil {
			session.TransType = TRANS_TYPE_TCP
			if setupPath == aPath || aPath != "" && strings.LastIndex(setupPath, aPath) == len(setupPath)-len(aPath) {
				session.aRTPChannel, _ = strconv.Atoi(tcpMatchs[1])
				session.aRTPControlChannel, _ = strconv.Atoi(tcpMatchs[3])
			} else if setupPath == vPath || vPath != "" && strings.LastIndex(setupPath, vPath) == len(setupPath)-len(vPath) {
				session.vRTPChannel, _ = strconv.Atoi(tcpMatchs[1])
				session.vRTPControlChannel, _ = strconv.Atoi(tcpMatchs[3])
			} else {
				res.StatusCode = 500
				res.Status = fmt.Sprintf("SETUP [TCP] got UnKown control:%s", setupPath)
				logger.Printf("SETUP [TCP] got UnKown control:%s", setupPath)
			}
			logger.Printf("Parse SETUP req.TRANSPORT:TCP.Session.Type:%d,control:%s, AControl:%s,VControl:%s", session.Type, setupPath, aPath, vPath)
...
}
**如果只有视频流没有音频流，session.aRTPChannel、session.aRTPControlChannel成员必为0，推流端与服务器协商的session.vRTPChannel也为0；**

在接收推流端发送过来的RTP包位置，如下代码：
./rtsp/rtsp-session.go
func (session *Session) Start() {
...
			var pack *RTPPack
			switch channel {
			case session.aRTPChannel:
				pack = &RTPPack{
					Type:   RTP_TYPE_AUDIO,
					Buffer: rtpBuf,
				}
			case session.aRTPControlChannel:
				pack = &RTPPack{
					Type:   RTP_TYPE_AUDIOCONTROL,
					Buffer: rtpBuf,
				}
			case session.vRTPChannel:
				pack = &RTPPack{
					Type:   RTP_TYPE_VIDEO,
					Buffer: rtpBuf,
				}
			case session.vRTPControlChannel:
				pack = &RTPPack{
					Type:   RTP_TYPE_VIDEOCONTROL,
					Buffer: rtpBuf,
				}
			default:
				logger.Printf("unknow rtp pack type, %v", pack.Type)
				continue
			}
...
｝
**由于session.aRTPChannel与session.vRTPChannel的值都被设置为0，此时当收到视频包时会导致RTPPack.Type成员被错误的设置成了RTP_TYPE_AUDIO，如果想在服务转发时根据RTPPack.Type做一些事情时就会导致逻辑错误。**

**修改建议：**
Session 结构的vRTPChannel/vRTPControlChannel/aRTPChannel/aRTPControlChannel的值最终是都是由推拉流的客户端确定，那么可以在初始化时设置为-1.
func NewSession(server *Server, conn net.Conn) *Session {
...
session := &Session{
                 ....
		vRTPChannel: -1,
		vRTPControlChannel: -1,
		aRTPChannel:-1,
		aRTPControlChannel:-1,
                 ....
...
}

**Comment by milkywayriver** [comment]
已按照您的思路做修改。 测试通过
