### ISSUE TITLE
你好，请问windows下能配置程序监听IP吗？

### ISSUE THREAD

**Issue by beefsteak** [EasyDarwin/EasyDarwin#126]
机器上有一个公网IP和一个局域网IP，程序默认获取到了局域网IP，如何指定公网IP？

**Comment by LinChengChun** [comment]
打开端口映射，看下通过外网ip能否访问，如果可以访问到EasyDarwin，那么就不用指定了。

**Comment by beefsteak** [comment]
但如果有2个外网IP的情况，这个时候我想选其中一个IP来用，端口映射略显麻烦了点。

**Comment by milkywayriver** [comment]
在RTSPServer或者HTTP Server启动的地方，指定IP地址。
现在是这样的：
addr, err := net.ResolveTCPAddr("tcp", fmt.Sprintf(":%d", server.TCPPort))
地址留空，表示取本机默认地址；你可以指定某个地址，类似"1.2.3.4:554"

**Comment by beefsteak** [comment]
懂了 谢谢
