### ISSUE TITLE
使用第三方拉流会控制台会报错，网络失败

### ISSUE THREAD

**Issue by dxfdsj** [EasyDarwin/EasyDarwin#127]
windows版本的EasyDarwin，在页面上拉流分发的视频流，用vlcPlayer播放，控制管理平台会弹出网络失败，推出的视频流也会消失，这个怎么解决呢？

**Comment by milkywayriver** [comment]
请发下日志

**Comment by dxfdsj** [comment]
之前用的版本是 EasyDarwin-windows-8.1.0-1811292235，昨天经过指导，下载了EasyDarwin-8.1.0-1811292237，这个服务启动之后，这个情况不再出现了。
