### ISSUE TITLE
可以编译运行在MIPS平台吗？

### ISSUE THREAD

**Issue by WK-LLP** [EasyDarwin/EasyDarwin#129]
我尝试编译mips架构的程序，不过报错了，请问在mips平台上可以使用吗？

GOOS=linux GOARCH=mipsle go build

github.com/EasyDarwin/EasyDarwin/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/flock.go:18:42: undefined: Flock_t
vendor/golang.org/x/sys/unix/lsf_linux.go:14:28: undefined: SockFilter
vendor/golang.org/x/sys/unix/lsf_linux.go:18:36: undefined: SockFilter
vendor/golang.org/x/sys/unix/lsf_linux.go:41:9: undefined: IFNAMSIZ

**Comment by milkywayriver** [comment]
没有测过。应该是什么版本不对导致。
参考下：
https://github.com/ipfs/go-ipfs/issues/4257
