### ISSUE TITLE
重提拉流分发遇到问题

### ISSUE THREAD

**Issue by yarafa** [EasyDarwin/EasyDarwin#130]
用的版本是EasyDarwin-windows-8.1.0-1901141151，出现错误如下。
![image](https://user-images.githubusercontent.com/45851564/53620684-d28b0880-3c2e-11e9-9a55-66b7fcd711f8.png)

日志如下：
[EasyDarwin] 2019/03/01 14:33:29 main.go:129: demon pull streams
[y2vas3rig]2019/03/01 14:33:50 rtsp-client.go:530: [OUT]>>>
OPTIONS rtsp://192.168.31.92:80/0 RTSP/1.0
CSeq: 1
Require: implicit-play
User-Agent: EasyDarwinGo/v8.1.

[y2vas3rig]2019/03/01 14:33:50 rtsp-client.go:572: <<<[IN]
RTSP/1.0 200 OK
CSeq: 1
Server: Rtsp Server 
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN, SET_PARAMETER

[y2vas3rig]2019/03/01 14:33:50 rtsp-client.go:530: [OUT]>>>
DESCRIBE rtsp://192.168.31.92:80/0 RTSP/1.0
CSeq: 2
Accept: application/sdp
User-Agent: EasyDarwinGo/v8.1.

[y2vas3rig]2019/03/01 14:33:50 rtsp-client.go:572: <<<[IN]
RTSP/1.0 200 OK
Cseq: 2
Server: Rtsp Server 1920*1080*30*4096
Content-Type: application/sdp
Content-length: 384
Content-Base: rtsp://192.168.31.92/0

[EasyDarwin] 2019/03/01 14:33:50 streams.go:75: Pull stream err :EOF

**Comment by milkywayriver** [comment]
拉流过程中对方主动关闭了，或者网络异常。

**Comment by yarafa** [comment]
没有异常，图中的rtsp地址是真实的摄像头的码流地址，用VLC能一直不停的播放。

**Comment by milkywayriver** [comment]
@yarafa 抓下vlc播放的包，比较下？

**Comment by yarafa** [comment]
@milkywayriver 我下载源码跟踪了，在rtsp-client.go中，下面的代码
headers = make(map[string]string)
headers["Accept"] = "application/sdp"
resp, err = client.Request("DESCRIBE", headers)

有的摄像头能获得结果，拉流成功，有的不能，即resp.Body为空，所以导致后边的解析出错，无法拉流。
请问没有结果的是什么原因呢，还是与摄像头的什么设置有关？
