### ISSUE TITLE
重新推流，原来本地生成的ts，m3u8文件被覆盖

### ISSUE THREAD

**Issue by swimfish09** [EasyDarwin/EasyDarwin#133]
使用ffmpeg推流到easydarwin一段时间后，如果因为某些原因推流端退出，再重新推流原来的文件会被覆盖，ts文件命名规则是不是应该取当前时间命名，m3u8文件以附加的方式保存

**Comment by milkywayriver** [comment]
应该是m3u8会被覆盖，但是ts文件不会。 你可根据ffmpeg的hls mux参数来设置m3u8保留的ts文件个数。参考：
https://ffmpeg.org/ffmpeg-formats.html#toc-hls-2

**Comment by swimfish09** [comment]
![image](https://user-images.githubusercontent.com/3916975/54096936-f695d900-43e8-11e9-9977-0c1307969d46.png)
不同时间推流的，ts文件和m3u8文件都被覆盖了。

**Comment by kakaqi** [comment]
我也遇到这个问题了，请问这个问题解决了吗？
