### ISSUE TITLE
转发视频卡顿

### ISSUE THREAD

**Issue by guoqing-rui** [EasyDarwin/EasyDarwin#14]
用darwin做转发服务器，无论是网络摄像头还是文件，vlc接收端卡顿，vlc日志显示picture is too late to displayed，貌似服务器时间戳处理有问题

**Comment by guoqing-rui** [comment]
还是有问题，原因应该是转发SDP时，没有加入解码用的profile-level-id,sps,pps等解码使用的信息。

**Comment by gentleboy** [comment]
我在装了ubuntu14.04的笔记本电脑上接了一个usb摄像头，将EasyDarwin的配置文件中的“selector_buffer_size_sec”参数设置为0，配置文件的其他部分未做修改。然后以root身份启动EasyDarwin。运行如下命令：ffmpeg -f v4l2 -i /dev/video1 -vcodec libx264 -preset:v ultrafast -tune:v zerolatency -r 24 -b:v 500K -s 320*240 -f rtsp rtsp://127.0.0.1/live.sdp。
       我开发了一个iOS的APP,运行在ipad上，在上面采用vlc播放器播放 rtsp://192.168.1.126/live.sdp 这个地址。播放开始的前几秒会出现花屏和马赛克的现象，之后正常。但是视频画面会有0.5秒左右的延迟，网络状况不好的时候会出现卡顿和马赛克，卡上几秒钟之后又可以正常播放，但是此时画面延迟达到2~4秒。每次发生卡顿后都会增加延迟时间。
        我目前想要达到的效果是局域网内的摄像头实时监控，延迟在1秒以内，实现一对一的视频传输就行，不需要支持多个客户端同时观看监控。请问有没有办法解决卡顿后延迟时间增加的问题？有没有地方可以设置EasyDarwin服务器每次和客户端恢复正常通信时，都将最新的视频帧推给客户端，而将已经过时的缓冲帧给覆盖掉？

**Comment by guoqing-rui** [comment]
客户端是否有默认缓存，网络不好时加大客户端缓存。另外不建议使用easydarwin和开源项目，问题很多，参考一下就可以。建议自己开发服务器。

发自我的 iPhone

**Comment by gentleboy** [comment]
谢谢您的建议！但是现在的问题是，我还是研一的学生，之前没做过流媒体方面的开发。。。老师也是建议我想办法直接用udp或者rtp传视频数据。我这段时间努力在网上寻找解决办法，却始终没找到比较好的方案。要我自己写代码去处理视频帧的封装和传输的话，我感到无从下手，很无助。。。我现在就只想做局域网内点对点的摄像头实时监控，延时在一秒以内。不知道您有没有类似开发经验？非常希望能够得到您的指点！万分感谢~

**Comment by guoqing-rui** [comment]
不考虑大并发和服务性能问题，自己做一个服务端，rtp包的处理可以考虑用jrtplib，rtsp用live555中的rtspclient和mediasession。

发自我的 iPhone

**Comment by xiejiashu** [comment]
客户端问题，建议参考一下EasyPlayer项目：https://github.com/EasyDarwin/EasyPlayer
