### ISSUE TITLE
EasyGoLib找不到，是什么问题

### ISSUE THREAD

**Issue by hongBry** [EasyDarwin/EasyDarwin#143]
@penggy 大神，您好，想问下这个EasyGoLib的包下不下来是什么原因

**Comment by hongBry** [comment]
@babosa 大神知道怎么解决吗

**Comment by sage-z** [comment]
@hongBry 我也遇到这个问题，搜了下github.com/penggy/EasyGoLib 已被作者移到github.com/ifree2017/EasyGoLib，并且有些函数已被删除，无法使用 ，@babosa 是否可以帮助更新下相关的项目依赖？感谢

**Comment by sage-z** [comment]
或考虑使用vendor包管理依赖

**Comment by SwordTwelve** [comment]
使用这个库放到vendor\github.com\penggy目录下，或者放到自行建立依赖目录




------------------ 原始邮件 ------------------
发件人: "zegapain"<notifications@github.com>;
发送时间: 2019年5月16日(星期四) 上午9:37
收件人: "EasyDarwin/EasyDarwin"<EasyDarwin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [EasyDarwin/EasyDarwin] EasyGoLib找不到，是什么问题 (#143)




@hongBry 我也遇到这个问题，搜了下github.com/penggy/EasyGoLib 已被作者移到github.com/ifree2017/EasyGoLib，并且有些函数已被删除，无法使用 ，@babosa 是否可以帮助更新下相关的项目依赖？感谢

**Comment by hongBry** [comment]
明白了，谢谢
