### ISSUE TITLE
转发丢包

### ISSUE THREAD

**Issue by guoqing-rui** [EasyDarwin/EasyDarwin#16]
用网络工具监控，用easydarwin进行转发时，接收的数据和发送的数据量不一致，发送数据明显比接收数据少。

**Comment by guoqing-rui** [comment]
转发的数据是darwin streaming server，mp4文件

**Comment by guoqing-rui** [comment]
问题已解决，扩大tcp buffer size范围。否则太大或太小的数据会被丢掉。

**Comment by xiejiashu** [comment]
ok

**Comment by ibanezsc** [comment]
这个问题是怎么修复呢，我有遇到了，而且转发丢包严重，经常出现卡顿

**Comment by milkywayriver** [comment]
> 这个问题是怎么修复呢，我有遇到了，而且转发丢包严重，经常出现卡顿

什么版本？GO版本吗？
