### ISSUE TITLE
关于系统的发展建议

### ISSUE THREAD

**Issue by gy2331314** [EasyDarwin/EasyDarwin#160]
rtsp/rtsp-server.go内server的start方法中将rtsp编码至本机mu38path目录用于点播很不错的设计，但H5对于rtsp的支持不尽如意，如果能实现rtsp转推rtmp服务器（更改params，用-f flv rtmp://....），这对于easydarwin未来发展将会有莫大的帮助，望考虑

**Comment by babosa** [comment]
非常好的建议，欢迎加入到EasyDarwin社区，共同推进先进需求的实现与迭代；
