### ISSUE TITLE
mac终端执行启动操作失败

### ISSUE THREAD

**Issue by zhangwei941913953** [EasyDarwin/EasyDarwin#168]
mac终端执行启动操作，提示二进制文件无法执行。

admindeMacBook-Pro:EasyDarwin-linux-8.1.0-1901141151 admin$ ./easydarwin
-bash: ./easydarwin: cannot execute binary file
admindeMacBook-Pro:EasyDarwin-linux-8.1.0-1901141151 admin$ ./start.sh 
./start.sh: line 3: /Users/admin/media/EasyDarwin-linux-8.1.0-1901141151/easydarwin: cannot execute binary file
./start.sh: line 4: /Users/admin/media/EasyDarwin-linux-8.1.0-1901141151/easydarwin: cannot execute binary file

**Comment by mybedhome** [comment]
为什么关闭，我的也报这个错误

**Comment by zhengyongrui** [comment]
我也是，求解决

**Comment by ufoozhenghao** [comment]
+1
