### ISSUE TITLE
Service模式不生成sdp文件

### ISSUE THREAD

**Issue by pizixie** [EasyDarwin/EasyDarwin#19]
以Service模式运行EasyDarwin。
转发流到服务器后，不生成sdp文件。

**Comment by xiejiashu** [comment]
EasyDarwin里面Movies目录配置的是相对路径，一旦用后台/服务模式运行，相对的位置就是系统目录了，所以需要将easydarwin.xml中movie_folder配置成绝对路径；

**Comment by pizixie** [comment]
嗯，是在系统目录中找到了．SystemWOW64．
配置成绝对路径已成功运行．
