### ISSUE TITLE
只要存在SDP文件EasyRTSPClient就认为这是一个有效的RTSP流

### ISSUE THREAD

**Issue by happyhate** [EasyDarwin/EasyDarwin#21]
不管是否推流只要服务器存在SDP文件EasyRTSPClient就认为这是一个有效的RTSP流建议将SDP文件放在内存里

**Comment by xiejiashu** [comment]
已经这么做了，非常感谢您的建议，详细代码参考：EasyDarwin::QTSSReflectorModule::DoAnnounce方法和EasyDarwin::QTSSReflectorModule::DestroySession方法里面对sdp操作的方法；
