### ISSUE TITLE
為甚麼EasyDarwin會推錯streaming給client??

### ISSUE THREAD

**Issue by michaelhsiao6715** [EasyDarwin/EasyDarwin#23]
問題是這樣的:
IPCam A -> EasyPusher to EasyDarwin <-> Client A play with VLC (123.sdp)
同時間
Client B也向EasyDarwin要求撥放IPCam B的456.sdp,抓封包看456.sdp也確實推到EasyDarwin了，RTSP signaling也是對的,可是撥出來卻是123.sdp的內容!?
但是，如果IPCam A 的streaming是用FFMpeg推上去的話，就不會有這個問題，
還請版主解惑， Thanks!

**Comment by abc1225** [comment]
我也遇到了同样的问题，请问有进展了吗

**Comment by abc1225** [comment]
hello, 我的问题解决了，以下是我的解决方法，希望能对你有点帮助：
之前和服务端遇到的一系列问题，都是和服务端交互的rtsp协议的问题，通过官方提供的easyclient和服务器交互的协议流程参数，对比了我自己的客户端的交互参数， 

最后一个问题，是由于  发送的sdp信息时  -o 参数里的会话id为 0  
猜测：服务器端关于 客户端流的映射关系可能使用了该参数，0导致流的映射关系出了问题

**Comment by michaelhsiao6715** [comment]
Hi,
謝謝你的分享，
我的問題也解決了，解決方式是將client端推流的方式全都換成EasyPusher就好了，之前有部分client是用FFMpeg來推流的。

2016-04-12 2:26 GMT+08:00 abc1225 <notifications@github.com>:

**Comment by xiejiashu** [comment]
谢谢大家的解答，主要还是sdp里面参数的原因
