### ISSUE TITLE
支持加入用户自定义的算法模型吗？

### ISSUE THREAD

**Issue by mashuai191** [EasyDarwin/EasyDarwin#238]
比如，我有对视频分析的需求，做一些自己的算法模型，然后把模型运用到视频流上，这个功能支持吗？如果没有的话，怎么做二次开发？多谢！

**Comment by milkywayriver** [comment]
目前没有.建议实现方式:
实现自己的客户端拉流+解码后处理

**Comment by mashuai191** [comment]
多谢回复！看到EasyNVR 有类似的支持 https://github.com/EasyNVR/EasyAIFilter
