### ISSUE TITLE
拉模式转发模块EasyRelayModule可以单独拆出来用吗？

### ISSUE THREAD

**Issue by kerneldeveloper** [EasyDarwin/EasyDarwin#25]
我的毕业设计要用到RTSP视频转发功能（ffmpeg推送,Darwin Streaming Server转发,vlc播放），虽然老师的要求是直接使用Darwin Streaming Server就可以，但是我觉得如果可能的话还是自己写个简单的转发程序比较好。

我看了下RTSP和RTP协议，实在是太复杂了，恰好看到这个开源项目，于是想问问拉模式转发模块EasyRelayModule可以单独拆出来用吗，能够实现rtsp转发就好。谢谢各位。

**Comment by xiejiashu** [comment]
参考EasyPusher_RTSP功能，基本上就是你要的：https://github.com/EasyDarwin/EasyPusher
