### ISSUE TITLE
./easydarwin：无法执行二进制文件: 可执行文件格式错误

### ISSUE THREAD

**Issue by premeditate** [EasyDarwin/EasyDarwin#262]
银河麒麟V10系统
下载的是EasyDarwin-linux-8.1.0-1901141151.tar.gz
解压后执行./easydarwin，提示如题错误
猜测这是X86架构的，arm架构的是要自己编译吗？

**Comment by Imjiajiawang** [comment]
对的，go写的比较垃圾

**Comment by Imjiajiawang** [comment]
根本不管能不能编译

**Comment by premeditate** [comment]
编译不出来,最后使用ZLMediaKit做的流媒体服务器,这个很容易编译成功,使用也是很方便的.
