### ISSUE TITLE
EasyDarwin 添加的HLS列表在重启系统后丢失

### ISSUE THREAD

**Issue by zgxy9931** [EasyDarwin/EasyDarwin#27]
EasyDarwin 添加的HLS列表在系统重启后丢失。不论是注册为Windows服务还是使用start.bat启动，添加的内容在系统关闭后均会出现丢失问题。

**Comment by xiejiashu** [comment]
EasyDarwin没有做列表保存功能，网上有其他EasyDarwin用户实现好的列表保存功能，例如：http://www.cnblogs.com/newsea/p/5340626.html
