### ISSUE TITLE
如何编译生成EasyDarwin可执行文件?

### ISSUE THREAD

**Issue by shiqishao** [EasyDarwin/EasyDarwin#275]
如何编译生成EasyDarwin可执行文件?(以go1.19.5为例)

1.下载go并配置环境变量 https://go.dev/dl/go1.19.5.linux-amd64.tar.gz
具体过程见go官网

2.执行go env 查看你的$GOPATH(我的是/home/setn/go)

3.cd /home/setn/go && mkdir -p src/github.com/EasyDarwin && cd src/github.com/EasyDarwin

4.git clone https://github.com/EasyDarwin/EasyDarwin.git --depth=1

5.cd EasyDarwin

6.编译：GO111MODULE=off GOARCH=amd64 go build或者GO111MODULE=off  go build

7.如果你想在x86编译arm64的，则执行GO111MODULE=off GOARCH=arm64 go build，此时会发现报错：
vendor/github.com/penggy/EasyGoLib/utils/log_linux.go:14:16: undefined: syscall.Dup2
需要修改代码：vim vendor/github.com/penggy/EasyGoLib/utils/log_linux.go
第14行：err = syscall.Dup2(int(logFile.Fd()), int(os.Stderr.Fd()))
改为：err = syscall.Dup3(int(logFile.Fd()), int(os.Stderr.Fd()),0)

8.重新执行：GO111MODULE=off GOARCH=arm64 go build

9.此时在当前目录下会编译生成EasyDarwin可执行文件

**Comment by dlnufox** [comment]
赞
