### ISSUE TITLE
The latest version build error on Ubuntu with /Buildit x64

### ISSUE THREAD

**Issue by daneric** [EasyDarwin/EasyDarwin#29]
mkdir -p build/x64/GNU-Linux/Server.tproj
rm -f "build/x64/GNU-Linux/Server.tproj/QTSServer.o.d"
g++ -pipe -Wall -Wno-format-y2k   -c -O2 -DCOMMON_UTILITIES_LIB -DDSS_USE_API_CALLBACKS -D_REENTRANT -D__USE_POSIX -D__linux__ -I../HTTPUtilitiesLib -I../CommonUtilitiesLib -IServer.tproj -IQTFileLib/ -IRTPMetaInfoLib/ -IPrefsSourceLib/ -IAPIStubLib/ -IAPICommonCode/ -IRTCPUtilitiesLib/ -IRTSPClientLib/ -IAPIModules/QTSSFileModule/ -IAPIModules/QTSSHttpFileModule/ -IAPIModules/QTSSAccessModule/ -IAPIModules/QTSSAccessLogModule/ -IAPIModules/QTSSPOSIXFileSysModule -IAPIModules/QTSSAdminModule/ -IAPIModules/QTSSReflectorModule/ -IAPIModules/QTSSWebStatsModule/ -IAPIModules/QTSSWebDebugModule/ -IAPIModules/QTSSFlowControlModule/ -IAPIModules/QTSSMP3StreamingModule/ -IAPIModules/EasyHLSModule -IAPIModules/EasyRelayModule -IInclude -I. -I../Include -I../EasyProtocol/Include -I../EasyProtocol/jsoncpp/include -include ../Include/PlatformHeader.h -MMD -MP -MF "build/x64/GNU-Linux/Server.tproj/QTSServer.o.d" -o build/x64/GNU-Linux/Server.tproj/QTSServer.o Server.tproj/QTSServer.cpp
Server.tproj/QTSServer.cpp:67:27: fatal error: EasyCMSModule.h: 没有那个文件或目录
 #include "EasyCMSModule.h"
                           ^
compilation terminated.
make[1]: **\* [build/x64/GNU-Linux/Server.tproj/QTSServer.o] 错误 1
make[1]:正在离开目录 `/home/adesk/EasyDarwin/EasyDarwin'
make: **\* [.build-conf] 错误 2

**Comment by 523412907** [comment]
我也遇到同样的错误，看提交记录，应该是新的CMS模块的改动引起的。已经提了一个ticket

**Comment by eiie** [comment]
在Server.tproj/QTSServer.cpp文件中，把与EasyCMS相关的代码注释掉就可以了

**Comment by 523412907** [comment]
Hi,

Got it. I will try.

Thanks.
Brs,
Rocky

**Comment by daneric** [comment]
I have resolved the problem. Thx very much!

**Comment by xiejiashu** [comment]
用最新归档的版本：https://github.com/EasyDarwin/EasyDarwin/releases/tag/v7.0.5，目前为新版本正在迭代中，所以，有很多不稳定的因素在里面

**Comment by Tinywan** [comment]
@babosa 用最新归档的版本：https://github.com/EasyDarwin/EasyDarwin/releases/tag/v7.0.5，链接打不开，页面404
