### ISSUE TITLE
EasyDarwin-7.0.5 ubuntu 14.04下编译错误问题

### ISSUE THREAD

**Issue by jzsjiale** [EasyDarwin/EasyDarwin#30]
EasyDarwin-7.0.5-Build16.0518  中 EasyCMS 编译出错；./Buildit x64    如下：

In file included from Server.tproj/HTTPSessionInterface.h:27:0,
                 from Server.tproj/HTTPSession.h:25,
                 from Server.tproj/HTTPSession.cpp:12:
../CommonUtilitiesLib/OSRefTableEx.h:47:8: warning: extra tokens at end of #endif directive [enabled by default]
 #endif _OSREFTABLEEX_H_
        ^
In file included from Server.tproj/HTTPSession.cpp:13:0:
Server.tproj/QTSServerInterface.h:64:20: fatal error: hiredis.h: No such file or directory
 #include"hiredis.h"
                    ^
compilation terminated.
make[1]: **\* [build/x64/GNU-Linux/Server.tproj/HTTPSession.o] Error 1
make[1]: Leaving directory `/root/sources/EasyDarwin-7.0.5/EasyCMS'
make: **\* [.build-conf] Error 2

请问如何解决呢，谢谢！

**Comment by xiejiashu** [comment]
5月底会完整发布EasyCMS，目前还在各个模块开发中，尚未整体运行

**Comment by babosa** [comment]
使用最新node.js版本
