### ISSUE TITLE
为什么没有EasyRTMP模块了呢，rtmp推流如何处理呢？

### ISSUE THREAD

**Issue by jzsjiale** [EasyDarwin/EasyDarwin#31]
为什么没有EasyRTMP模块了呢，rtmp向服务器推流如何处理呢？
服务器能否支持rtmp呢？
谢谢！

**Comment by qingzhizhenhun** [comment]
EasyDarwin只支持推拉RTSP流,不支持RTMP流,RTMP流的产品可以去紫鲸开放平台查看,官网是www.pvale.com

**Comment by gy2331314** [comment]
easydarwin设计的目的就是rtsp的推拉，如果为了rtmp推流，可以更改rtsp/rtsp-server.go，让easydarwin将rtsp流转推至nginx-rtmp的application，实现rtmp推流
