### ISSUE TITLE
EasyDarwin api/getrtsppushsessions bug.

### ISSUE THREAD

**Issue by hanyubao** [EasyDarwin/EasyDarwin#33]
I started easydarwin program, and ran an application to call   **api/getrtsppushsessions** interfaces **every second**, several hours later, the interface did not  provide the rtsppushsessions content any more.
It seems that this bug has relation with "**QSHeap.cpp**".
Here is the -d output when the interface is called.
![1234](https://cloud.githubusercontent.com/assets/1953649/15989642/257a6c90-30af-11e6-8721-2f8f67e0a416.png)
ps: easydarwin edition is release 7.0.5,os is windows 2008 r2 x64. 
May this feedback helps.
Thanks!

**Comment by penggy** [comment]
Use the newest NodeJS version, please.
