### ISSUE TITLE
这是一个BUG？

### ISSUE THREAD

**Issue by jianqiang2** [EasyDarwin/EasyDarwin#37]
使用最新版本EasyDarwin的代码部署成功之后发现在配置web里的HLS直播配置无效，通过调试发现
最新的EasyDarwin代码已经去掉了HLS模块，模块初始化时没有初始化HLS模块，导致以下语句获取不到Hls模块对象：
 sHLSModulePrefs = QTSSModuleUtils::GetModulePrefsObject(QTSSModuleUtils::GetModuleObjectByName("EasyHLSModule"));
这是一个bug吗？

**Comment by gpr321** [comment]
我也有同样的问题

**Comment by babosa** [comment]
https://github.com/EasyDarwin/EasyDarwin README里面有说明
“EasyDarwin流媒体服务器原来带有非开源SDK的EasyRelayModule和EasyHLSModule已经移除，新版本的拉模式转发和HLS直播模块功能将全部采用开源live555/ffmpeg等开源项目结合实现，敬请期待！
”
