### ISSUE TITLE
EasyDarwin支持h265吗

### ISSUE THREAD

**Issue by HuYuHua** [EasyDarwin/EasyDarwin#40]
如标题。现在EasyDarwin支持h265吗？

**Comment by yypnathan** [comment]
同问。我用ffmpeg往easydarwin推h265的流，能够通过rtsp的url播放，但是无法正常进行hls切片。我猜测是easyHls不支持h265

**Comment by vvhh2002** [comment]
HLS 标准现在是264 好不好。

**Comment by penggy** [comment]
EasyDarwin  作为 RTSP 流分发服务器, 本身不限制视频的编码格式, 只是暂时只对 h264 编码的视频数据做了GOP cache, 提供更快的起播速度而已
