### ISSUE TITLE
easyCMS在build时报错

### ISSUE THREAD

**Issue by flyinglove** [EasyDarwin/EasyDarwin#44]
centos7，easyv0.7.5版，先是报错`hiredis.h`没找到，我把`hiredis.h`拷到这个目录下，然后是报`QTSSAuthModule.h`这个文件找不到，同样是将这个文件拷到了当前目录，然后是报`QTSServer.cpp`中没有名为`GetRunGroupName`的成员，这下我就不知道该怎么解决了，

**Comment by babosa** [comment]
下载最新版本的EasyDarwin代码进行编译
