### ISSUE TITLE
EasyDarwin

### ISSUE THREAD

**Issue by gitHublee** [EasyDarwin/EasyDarwin#5]
Buildit cannot work (Linux)

**Comment by xiejiashu** [comment]
a moment

**Comment by zhaobnm** [comment]
好像还不能编译？

**Comment by feng905** [comment]
脚本文件是DOS格式的, 即每一行的行尾以\n\r来标识, 其ASCII码分别是0x0D, 0x0A.

解决方法：
vim filename
然后用命令
:set ff? #可以看到dos或unix的字样. 如果的确是dos格式的。
然后用
:set ff=unix #把它强制为unix格式的, 然后存盘退出。
再次运行脚本

**Comment by xiejiashu** [comment]
Thx！
