### ISSUE TITLE
v7.1.16.1111 无法正常结束推流

### ISSUE THREAD

**Issue by jingyuzhu** [EasyDarwin/EasyDarwin#51]
rtsp 在结束推流发送teardown请求时，服务端会报 500错误

#C->S:
#time: ms=31538 date=Mon, 05 Dec 2016 05:53:50 GMT
#server: ip=172.28.1.208 port=2554
#client: ip=172.28.1.181 port=56218
OPTIONS rtsp://172.28.1.208:2554/1.sdp RTSP/1.0\r\n
CSeq: 1\r\n
User-Agent: Lavf56.40.101\r\n
\r\n

#S->C:
#time: ms=31538 date=Mon, 05 Dec 2016 05:53:50 GMT
RTSP/1.0 200 OK\r\n
Server: EasyDarwin/7.1 (Build/16.1111; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 1\r\n
Public: DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, OPTIONS, ANNOUNCE, RECORD\r\n
\r\n

#C->S:
#time: ms=31540 date=Mon, 05 Dec 2016 05:53:50 GMT
#server: ip=172.28.1.208 port=2554
#client: ip=172.28.1.181 port=56218
ANNOUNCE rtsp://172.28.1.208:2554/1.sdp RTSP/1.0\r\n
Content-Type: application/sdp\r\n
CSeq: 2\r\n
User-Agent: Lavf56.40.101\r\n
Content-Length: 492\r\n
\r\n

#S->C:
#time: ms=31580 date=Mon, 05 Dec 2016 05:53:50 GMT
RTSP/1.0 200 OK\r\n
Server: EasyDarwin/7.1 (Build/16.1111; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 2\r\n
\r\n

#C->S:
#time: ms=31582 date=Mon, 05 Dec 2016 05:53:50 GMT
#server: ip=172.28.1.208 port=2554
#client: ip=172.28.1.181 port=56218
SETUP rtsp://172.28.1.208:2554/1.sdp/streamid=0 RTSP/1.0\r\n
Transport: RTP/AVP/UDP;unicast;client_port=10448-10449;mode=record\r\n
CSeq: 3\r\n
User-Agent: Lavf56.40.101\r\n
\r\n

向redis中添加推流名称1
QTSSReflectorModule.cpp:DoSetup Session =0x7fdbd0000f20 refcount=1

#S->C:
#time: ms=31586 date=Mon, 05 Dec 2016 05:53:50 GMT
RTSP/1.0 200 OK\r\n
Server: EasyDarwin/7.1 (Build/16.1111; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 3\r\n
Cache-Control: no-cache\r\n
Session: 7776565544653996933\r\n
Date: Mon, 05 Dec 2016 05:53:50 GMT\r\n
Expires: Mon, 05 Dec 2016 05:53:50 GMT\r\n
Transport: RTP/AVP/UDP;unicast;mode=record;source=172.28.1.208;client_port=10448-10449;server_port=6972-6973\r\n
\r\n

#C->S:
#time: ms=31589 date=Mon, 05 Dec 2016 05:53:50 GMT
#server: ip=172.28.1.208 port=2554
#client: ip=172.28.1.181 port=56218
SETUP rtsp://172.28.1.208:2554/1.sdp/streamid=1 RTSP/1.0\r\n
Transport: RTP/AVP/UDP;unicast;client_port=10450-10451;mode=record\r\n
CSeq: 4\r\n
User-Agent: Lavf56.40.101\r\n
Session: 7776565544653996933\r\n
\r\n

QTSSReflectorModule.cpp:DoSetup Session =0x7fdbd0000f20 refcount=1

#S->C:
#time: ms=31589 date=Mon, 05 Dec 2016 05:53:50 GMT
RTSP/1.0 200 OK\r\n
Server: EasyDarwin/7.1 (Build/16.1111; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 4\r\n
Session: 7776565544653996933\r\n
Cache-Control: no-cache\r\n
Date: Mon, 05 Dec 2016 05:53:50 GMT\r\n
Expires: Mon, 05 Dec 2016 05:53:50 GMT\r\n
Transport: RTP/AVP/UDP;unicast;mode=record;source=172.28.1.208;client_port=10450-10451;server_port=6974-6975\r\n
\r\n

#C->S:
#time: ms=31591 date=Mon, 05 Dec 2016 05:53:50 GMT
#server: ip=172.28.1.208 port=2554
#client: ip=172.28.1.181 port=56218
RECORD rtsp://172.28.1.208:2554/1.sdp RTSP/1.0\r\n
Range: npt=0.000-\r\n
CSeq: 5\r\n
User-Agent: Lavf56.40.101\r\n
Session: 7776565544653996933\r\n
\r\n

QTSSReflectorModule.cpp:DoPlay Session =0x7fdbd0000f20 refcount=1

#S->C:
#time: ms=31591 date=Mon, 05 Dec 2016 05:53:50 GMT
RTSP/1.0 200 OK\r\n
Server: EasyDarwin/7.1 (Build/16.1111; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 5\r\n
Session: 7776565544653996933\r\n
RTP-Info: url=rtsp://172.28.1.208:2554/1.sdp/streamid=0,url=rtsp://172.28.1.208:2554/1.sdp/streamid=1\r\n
\r\n

**#C->S:
#time: ms=43913 date=Mon, 05 Dec 2016 05:54:02 GMT
#server: ip=172.28.1.208 port=2554
#client: ip=172.28.1.181 port=56218
TEARDOWN rtsp://172.28.1.208:2554/1.sdp RTSP/1.0\r\n
CSeq: 6\r\n
User-Agent: Lavf56.40.101\r\n
Session: 7776565544653996933\r\n
\r\n**

**#S->C:
#time: ms=43913 date=Mon, 05 Dec 2016 05:54:02 GMT
RTSP/1.0 500 Internal Server Error\r\n
Server: EasyDarwin/7.1 (Build/16.1111; Platform/Linux; Release/EasyDarwin; State/Development; )\r\n
Cseq: 6\r\n
Session: 7776565544653996933\r\n
Connection: Close\r\n
Content-length: 62\r\n
\r\n**
There is no QTSS API module installed to process this request.RTSPSession fObjectHolders:1 !
RTSPSessionHandler::Release()
~RTSPSessionHandler()
没有客户端观看当前转发媒体
QTSSReflectorModule.cpp:RemoveOutput Session =0x7fdbd0000f20 refcount=0
QTSSReflectorModule.cpp:RemoveOutput UnRegister and delete session =0x7fdbd0000f20 refcount=0
从redis中删除推流名称1
RTSPSession fObjectHolders:0 !
RTSPSesion Run Return -1

**Comment by babosa** [comment]
使用最新node.js版本的EasyDarwin，I/O性能更强和接口更加丰富
