### ISSUE TITLE
RTSP/1.0 500 Internal Server Error

### ISSUE THREAD

**Issue by hqiang216** [EasyDarwin/EasyDarwin#56]
mp4点播，中间有这个错误，VLC提示无法打开MRL...这是为什么？

**Comment by fayfive** [comment]
我布局到阿里云，rtsp，一连接会出现这个情况，不知道你是怎样解决？

**Comment by penggy** [comment]
DNS results in the problem. When the Client use ip to connect, it succeed. #79
