### ISSUE TITLE
easydarwin使用推模式，客户端刚开始播放的第一秒花屏

### ISSUE THREAD

**Issue by matthew2013** [EasyDarwin/EasyDarwin#6]
问题描述：
easydarwin使用推模式，客户端刚开始播放的第一秒花屏
出现环境：
darwin服务器是在win7下运行的； 客户端使用的是vlc； 全部组件都是在局域网的环境下； ffmpeg的命令是：ffmpeg -rtsp_transport tcp -i "rtsp://admin:12345@172.16.8.245:554/Streaming/Channels/1?transportmode=unicast&profile=Profile_1" -f rtsp rtsp://172.16.8.114/test.sdp； 摄像头使用的是海康的摄像头。

**Comment by xiejiashu** [comment]
如果想要客户端一开始不花屏，服务器需要第一帧就传给客户端关键帧，或者客户端先过滤掉非关键帧，再开始解码显示

**Comment by matthew2013** [comment]
好的，请群主考虑怎么优化

**Comment by xiejiashu** [comment]
已经实现，请帮忙测试；
