### ISSUE TITLE
docker封装easydarwin

### ISSUE THREAD

**Issue by bkyifanleo** [EasyDarwin/EasyDarwin#60]
用easydarwin 作为rtsp服务器接受live555推送的视频流。
这一步没问题。
将它封装到docker里面，easydarwin报错404.
我映射的端口是-p 8554:8554 -p 8080:8080
具体命令 
docker run --rm -ti -v /home/zyf/video/:/data1 -p 8554:8554 -p 8554:8554/udp -p 8080:8080 -p 8080:8080/udp chanyuepo/easydarwin:v6
我想问一下easydarwin有没有docker封装的例子，或者端口这一块是否有问题。
谢谢

**Comment by bkyifanleo** [comment]
解决了。
1 需要指定docker 网络模式&端口
2 需要确定docker使用宿主权限

**Comment by wzkun** [comment]
请问你的dockerfile是怎么写的，可以看一下文件源码吗？

**Comment by song264516** [comment]
> @yifa-n 请问你的dockerfile是怎么写的，可以看一下文件源码吗？

您好，Dockerfile能分享下吗
