### ISSUE TITLE
VLC可以直接从运行EasyCamera的摄像头上读取RTSP流吗？

### ISSUE THREAD

**Issue by xmflsct** [EasyDarwin/EasyDarwin#64]
VLC可以直接从运行EasyCamera的摄像头上读取RTSP流吗？

**Comment by zds05** [comment]
EasyCamera应该没有提供作为rtsp服务的功能

**Comment by jinlong0813** [comment]
可以使用EasyIPCamera工程。EasyIPCamera本身就是一个rtsp server， 视频源可以是读文件、摄像头SDK获取流、其他rtsp流等。https://github.com/EasyDarwin/EasyIPCamera
