### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by lixingshi** [EasyDarwin/EasyDarwin#67]
av_interleaved_write_frame(): Can't assign requested address
frame=    1 fps=0.0 q=-1.0 Lsize=N/A time=-00:00:00.23 bitrate=N/A speed=N/A    
video:69kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

ffmpeg推流出现这个问题

**Comment by jinlong0813** [comment]
用最新代码。 并以TCP方式推流。
