### ISSUE TITLE
我表示很遗憾，这个开源平台看起来不错，怎么文档如此简单。

### ISSUE THREAD

**Issue by curtis2** [EasyDarwin/EasyDarwin#69]

**Comment by curtis2** [comment]
这就是服务器的文档！！https://github.com/EasyDarwin/EasyDarwin/blob/master/EasyDarwin_Cloud_Windows.md

**Comment by bgc8080** [comment]
因为就是想要你买商业版呀

**Comment by zhanjx1314** [comment]
csdn上有视频教学，可以去看看

发自我的 iPhone

在 2017年8月22日，下午10:03，Alan <notifications@github.com<mailto:notifications@github.com>> 写道：


因为就是想要你买商业版呀

**Comment by tiger7chan** [comment]
csdn上面的视频早就没了，群里倒是有，但视频教学都是老版本的，新版本的都没有。至少上个月是这样的哈，虽然只过了一个月，也还是希望他们能更新的（然而不太可能）。

**Comment by xiaole51** [comment]
貌似多数开源软件的通病.
TVH的文档也很简陋

**Comment by blankxyz** [comment]
国产开源其实就是做广告，其实还是要卖才告诉你怎么用，并不是真的开源，呵呵

**Comment by penggy** [comment]
我唯能做的, 就是默默关闭
