### ISSUE TITLE
Can't Forward normal rtsp stream

### ISSUE THREAD

**Issue by jimying** [EasyDarwin/EasyDarwin#7]
Now i use easydarwin edit device.xml, add camera rtsp url, can forward  ip camera rtsp live stream, vlc can play it.
But if i edit device.xml, and add one rule to play normal rtsp url, It can't play.

rtsp url ：rtsp://admin:12345@124.133.33.114:6554/Streaming/tracks/101?starttime=20150710t082010z&endtime=20150710t084510z

I want to know if current forward module only support camera?
why not support normal rtsp forwarding?

**Comment by xiejiashu** [comment]
got it, we will fix this later in this month

**Comment by jimying** [comment]
This is be sure an issue.
Follow steps will also appear error about the QTSSOnDemandRelayModule:
Two easyDarwin server 
1. one server(eg, ip: 192.168.1.8) pull from an ip camera
     device.xml add:
     <Device id="100" name="test" url="rtsp://admin:12345@124.133.33.114:6554/Streaming/Channels/201"/>

2. the other one (eg, ip:192.168.1.9) pull  from the first server the ip camera url
    device.xml add:
      <Device id="100" name="test" url="rtsp://192.168.1.8/test"/>

3. vlc play the rtsp url: rtsp://192.168.1.9/test
    if the proxy module is well,  it should be about to play, but the second server error, the first server has rtp data coming, the second error log as follow:
    [URL:"rtsp://192.168.1.9/test/"]: Initiated the "video/H264" subsession (client ports 45818-45819)
    [URL:"rtsp://192.168.1.9/test/"]: Failed to set up the "video/H264" subsession: 400 Bad Request
   [URL:"rtsp://192.168.1.9/test/"]: Failed to start playing session: No RTSP session is currently in progress


Maybe this log will give some help
-----------------

**Comment by jimying** [comment]
The above two darwin servers , error,  I find that in the QTSSOnDemandRelayModule.cpp,   OnSetup(),  theDigitStr is NULL,   Could't get trackID.   I  debug it  in a ugly method: When theDigitStr  is NULL, not return,  and  set trackID to 1,  test  only video, success.

Why qtssRTSPReqFileDigit value  is   NULL? 
I think there should be a formal method to solve it.
