### ISSUE TITLE
EasyCMS无法登录

### ISSUE THREAD

**Issue by cobrayang** [EasyDarwin/EasyDarwin#71]
根据文档配置启动linux版本时候，发现没法登陆。
尝试了admin／admin不对。
请问能否支持一下，提供一下初始的管理员账户。
谢谢！
![2017-07-19 14 24 07](https://user-images.githubusercontent.com/30259379/28445454-08d7d38a-6df7-11e7-96e5-ac5b932b70fc.png)

**Comment by tandes** [comment]
建议你F12调试看看。我之前本地登录提示密码错误，但是实际看控制台是服务的问题，右侧弹框的登录失败信息不准确。

**Comment by cobrayang** [comment]
是不是因为没有module，导致服务不正常。
### “2017-07-24 11:23:34: WARNING: No module folder exists.
2017-07-24 11:23:34: INFO: Module Loaded...EasyRedisModule [static]Connect Redis success
2017-07-24 11:23:34: INFO: EasyCMS Service done starting up“

**Comment by babosa** [comment]
请采用最新的golang版本
