### ISSUE TITLE
EasyDarwin出现大量CLOSE_WAIT

### ISSUE THREAD

**Issue by gavinshao111** [EasyDarwin/EasyDarwin#72]
EasyDarwin有时候会出现大量CLOSE_WAIT，不清楚是对推流端还是播放端的TCP没关闭。出现大量的CLOSE_WAIT后，新的推流端建立TCP准备开始RTSP会话时，读不到任何回应。

**Comment by babosa** [comment]
此bug已修复

**Comment by litecy** [comment]
这个bug是在哪个commit修复的？
