### ISSUE TITLE
【急急急急】服务器启动成功了，easydarwin.xml也配置了，为什么还是不能进入控制台？

### ISSUE THREAD

**Issue by wujiatao** [EasyDarwin/EasyDarwin#73]
现在想搭建个服务器用于测试流媒体业务，服务器用easydarwin，movies下面放有需要传输的.wmv视频文件，客服端播放器采用VLC，但是现在有个问题，访问http://10.9.194.174:554/提示：
RTSP/1.0 400 Bad Request
Server: EasyDarwin/7.0.5 (Build/16.0518; Platform/Win32; Release/EasyDarwin; State/Development; )
Cseq: 
Connection: Close
麻烦哪位高手帮忙分析下，多谢！

**Comment by zhanjx1314** [comment]
是不是媒体文件的问题呢

发自我的 iPhone

在 2017年8月17日，下午8:36，wujiatao <notifications@github.com<mailto:notifications@github.com>> 写道：


现在想搭建个服务器用于测试流媒体业务，服务器用easydarwin，movies下面放有需要传输的.wmv视频文件，客服端播放器采用VLC，但是现在有个问题，访问http://10.9.194.174:554/提示：<http://10.9.194.174:554/%E6%8F%90%E7%A4%BA%EF%BC%9A>
RTSP/1.0 400 Bad Request
Server: EasyDarwin/7.0.5 (Build/16.0518; Platform/Win32; Release/EasyDarwin; State/Development; )
Cseq:
Connection: Close
麻烦哪位高手帮忙分析下，多谢！

**Comment by babosa** [comment]
用最新的golang版本
