### ISSUE TITLE
Error configure stream, RTSP/1.0 500 Internal Server Error

### ISSUE THREAD

**Issue by jp1017** [EasyDarwin/EasyDarwin#79]
We use EasyDarwin Server, when the client send `SETUP` command, the server response 500, here is my `SETUP` config: 

```
SETUP rtsp://video.xxxx.com:10554/107700000016_11.sdp/streamid=0 RTSP/1.0
                                                                    Transport: RTP/AVP/TCP;interleaved=0-1;mode=record
                                                                    CSeq: 3
                                                                    Content-Length: 0
```

**Comment by jp1017** [comment]
same to https://github.com/EasyDarwin/EasyDarwin/issues/56, but no response, so I recreate one.

**Comment by jp1017** [comment]
So, what's the correct `SETUP` config.

**Comment by LinChengChun** [comment]
Which client do you used?Could you test by another client ?

**Comment by zhanjx1314** [comment]
vlc and live555

发自我的 iPhone

在 2017年12月25日，下午5:28，Lambo <notifications@github.com<mailto:notifications@github.com>> 写道：


Which client do you used?Could you test by another client ?

**Comment by jp1017** [comment]
server: easydarwin
client: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/103

**Comment by jp1017** [comment]
DNS results in the problem. When the Client use ip to connect, it succeed.
