### ISSUE TITLE
Ubuntu16.04.3 中 EasyDarwin 编译出错

### ISSUE THREAD

**Issue by topgun97** [EasyDarwin/EasyDarwin#82]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

EasyDarwin-7.3.17.0325 中 EasyCMS 编译出错；./Buildit x64 如下：

"make"  -f nbproject/Makefile-x64.mk x64/libCommonUtilitiesLib.a
make[1]: Entering directory '/home/topgun/EasyDarwin-7.3.17.0325/CommonUtilitiesLib'
make[1]: 'x64/libCommonUtilitiesLib.a' is up to date.
make[1]: Leaving directory '/home/topgun/EasyDarwin-7.3.17.0325/CommonUtilitiesLib'
"make"  -f nbproject/Makefile-x64.mk x64/libeasyredisclient.a
make[1]: Entering directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyRedisClient'
make[1]: 'x64/libeasyredisclient.a' is up to date.
make[1]: Leaving directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyRedisClient'
"make"  -f nbproject/Makefile-x64.mk x64/libjsoncpp.a
make[1]: Entering directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyProtocol/jsoncpp'
make[1]: 'x64/libjsoncpp.a' is up to date.
make[1]: Leaving directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyProtocol/jsoncpp'
"make"  -f nbproject/Makefile-x64.mk x64/libEasyProtocol.a
make[1]: Entering directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyProtocol/EasyProtocol'
make[1]: 'x64/libEasyProtocol.a' is up to date.
make[1]: Leaving directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyProtocol/EasyProtocol'
"make"  -f nbproject/Makefile-x64.mk x64/easydarwin
make[1]: Entering directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyDarwin'
mkdir -p x64
g++ -pipe -Wall -Wno-format-y2k -std=c++11    -o x64/easydarwin build/x64/GNU-Linux/_ext/b9fc5c32/HTTPClientRequestStream.o build/x64/GNU-Linux/_ext/b9fc5c32/HTTPClientResponseStream.o build/x64/GNU-Linux/_ext/b9fc5c32/HTTPProtocol.o build/x64/GNU-Linux/_ext/b9fc5c32/HTTPRequest.o build/x64/GNU-Linux/_ext/a7d13d49/RTSPProtocol.o build/x64/GNU-Linux/APICommonCode/QTAccessFile.o build/x64/GNU-Linux/APICommonCode/QTSSModuleUtils.o build/x64/GNU-Linux/APICommonCode/QTSSRollingLog.o build/x64/GNU-Linux/APICommonCode/SDPSourceInfo.o build/x64/GNU-Linux/APICommonCode/SourceInfo.o build/x64/GNU-Linux/APIModules/EasyCMSModule/EasyCMSModule.o build/x64/GNU-Linux/APIModules/EasyCMSModule/EasyCMSSession.o build/x64/GNU-Linux/APIModules/EasyRedisModule/EasyRedisModule.o build/x64/GNU-Linux/APIModules/QTSSAccessLogModule/QTSSAccessLogModule.o build/x64/GNU-Linux/APIModules/QTSSAccessModule/AccessChecker.o build/x64/GNU-Linux/APIModules/QTSSAccessModule/QTSSAccessModule.o build/x64/GNU-Linux/APIModules/QTSSAdminModule/AdminElementNode.o build/x64/GNU-Linux/APIModules/QTSSAdminModule/AdminQuery.o build/x64/GNU-Linux/APIModules/QTSSAdminModule/QTSSAdminModule.o build/x64/GNU-Linux/APIModules/QTSSAdminModule/frozen.o build/x64/GNU-Linux/APIModules/QTSSAdminModule/mongoose.o build/x64/GNU-Linux/APIModules/QTSSFlowControlModule/QTSSFlowControlModule.o build/x64/GNU-Linux/APIModules/QTSSPOSIXFileSysModule/QTSSPosixFileSysModule.o build/x64/GNU-Linux/APIModules/QTSSReflectorModule/QTSSReflectorModule.o build/x64/GNU-Linux/APIModules/QTSSReflectorModule/RCFSourceInfo.o build/x64/GNU-Linux/APIModules/QTSSReflectorModule/RTPSessionOutput.o build/x64/GNU-Linux/APIModules/QTSSReflectorModule/ReflectorSession.o build/x64/GNU-Linux/APIModules/QTSSReflectorModule/ReflectorStream.o build/x64/GNU-Linux/APIModules/QTSSReflectorModule/SequenceNumberMap.o build/x64/GNU-Linux/APIModules/QTSSWebDebugModule/QTSSWebDebugModule.o build/x64/GNU-Linux/APIStubLib/QTSS_Private.o build/x64/GNU-Linux/PrefsSourceLib/FilePrefsSource.o build/x64/GNU-Linux/PrefsSourceLib/XMLParser.o build/x64/GNU-Linux/PrefsSourceLib/XMLPrefsParser.o build/x64/GNU-Linux/QTFileLib/QTAtom.o build/x64/GNU-Linux/QTFileLib/QTAtom_dref.o build/x64/GNU-Linux/QTFileLib/QTAtom_elst.o build/x64/GNU-Linux/QTFileLib/QTAtom_hinf.o build/x64/GNU-Linux/QTFileLib/QTAtom_mdhd.o build/x64/GNU-Linux/QTFileLib/QTAtom_mvhd.o build/x64/GNU-Linux/QTFileLib/QTAtom_stco.o build/x64/GNU-Linux/QTFileLib/QTAtom_stsc.o build/x64/GNU-Linux/QTFileLib/QTAtom_stsd.o build/x64/GNU-Linux/QTFileLib/QTAtom_stss.o build/x64/GNU-Linux/QTFileLib/QTAtom_stsz.o build/x64/GNU-Linux/QTFileLib/QTAtom_stts.o build/x64/GNU-Linux/QTFileLib/QTAtom_tkhd.o build/x64/GNU-Linux/QTFileLib/QTAtom_tref.o build/x64/GNU-Linux/QTFileLib/QTFile.o build/x64/GNU-Linux/QTFileLib/QTFile_FileControlBlock.o build/x64/GNU-Linux/QTFileLib/QTHintTrack.o build/x64/GNU-Linux/QTFileLib/QTRTPFile.o build/x64/GNU-Linux/QTFileLib/QTTrack.o build/x64/GNU-Linux/RTCPUtilitiesLib/RTCPAPPNADUPacket.o build/x64/GNU-Linux/RTCPUtilitiesLib/RTCPAPPPacket.o build/x64/GNU-Linux/RTCPUtilitiesLib/RTCPAPPQTSSPacket.o build/x64/GNU-Linux/RTCPUtilitiesLib/RTCPAckPacket.o build/x64/GNU-Linux/RTCPUtilitiesLib/RTCPPacket.o build/x64/GNU-Linux/RTCPUtilitiesLib/RTCPSRPacket.o build/x64/GNU-Linux/RTPMetaInfoLib/RTPMetaInfoPacket.o build/x64/GNU-Linux/Server.tproj/GenerateXMLPrefs.o build/x64/GNU-Linux/Server.tproj/HTTPSession.o build/x64/GNU-Linux/Server.tproj/HTTPSessionInterface.o build/x64/GNU-Linux/Server.tproj/QTSSCallbacks.o build/x64/GNU-Linux/Server.tproj/QTSSDataConverter.o build/x64/GNU-Linux/Server.tproj/QTSSDictionary.o build/x64/GNU-Linux/Server.tproj/QTSSErrorLogModule.o build/x64/GNU-Linux/Server.tproj/QTSSExpirationDate.o build/x64/GNU-Linux/Server.tproj/QTSSFile.o build/x64/GNU-Linux/Server.tproj/QTSSMessages.o build/x64/GNU-Linux/Server.tproj/QTSSModule.o build/x64/GNU-Linux/Server.tproj/QTSSPrefs.o build/x64/GNU-Linux/Server.tproj/QTSSSocket.o build/x64/GNU-Linux/Server.tproj/QTSSUserProfile.o build/x64/GNU-Linux/Server.tproj/QTSServer.o build/x64/GNU-Linux/Server.tproj/QTSServerInterface.o build/x64/GNU-Linux/Server.tproj/QTSServerPrefs.o build/x64/GNU-Linux/Server.tproj/RTCPTask.o build/x64/GNU-Linux/Server.tproj/RTPBandwidthTracker.o build/x64/GNU-Linux/Server.tproj/RTPOverbufferWindow.o build/x64/GNU-Linux/Server.tproj/RTPPacketResender.o build/x64/GNU-Linux/Server.tproj/RTPSession.o build/x64/GNU-Linux/Server.tproj/RTPSessionInterface.o build/x64/GNU-Linux/Server.tproj/RTPStream.o build/x64/GNU-Linux/Server.tproj/RTSPRequest.o build/x64/GNU-Linux/Server.tproj/RTSPRequestInterface.o build/x64/GNU-Linux/Server.tproj/RTSPRequestStream.o build/x64/GNU-Linux/Server.tproj/RTSPResponseStream.o build/x64/GNU-Linux/Server.tproj/RTSPSession.o build/x64/GNU-Linux/Server.tproj/RTSPSessionInterface.o build/x64/GNU-Linux/Server.tproj/RunServer.o build/x64/GNU-Linux/Server.tproj/main.o -L../CommonUtilitiesLib/x64 -L../EasyProtocol/EasyProtocol/x64 -L../EasyProtocol/jsoncpp/x64 -LLib/x64 -L../EasyRedisClient/x64 -LLib -lCommonUtilitiesLib -lpthread -ldl -lstdc++ -lm -lcrypt -lEasyProtocol -ljsoncpp -leasyredisclient
../CommonUtilitiesLib/x64/libCommonUtilitiesLib.a(OSFileSource.o): In function `OSFileSource::Set(char const*)':
OSFileSource.cpp:(.text+0x10cb): undefined reference to `__warn_memset_zero_len'
../CommonUtilitiesLib/x64/libCommonUtilitiesLib.a(SDPUtils.o): In function `SDPContainer::Initialize()':
SDPUtils.cpp:(.text+0x78e): undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
nbproject/Makefile-x64.mk:153: recipe for target 'x64/easydarwin' failed
make[1]: *** [x64/easydarwin] Error 1
make[1]: Leaving directory '/home/topgun/EasyDarwin-7.3.17.0325/EasyDarwin'
nbproject/Makefile-x64.mk:150: recipe for target '.build-conf' failed
make: *** [.build-conf] Error 2

请问如何处置？谢谢！

**Comment by topgun97** [comment]
已解决。
删除原文件夹，重新编译即可。

**Comment by starmissw** [comment]
您好，我也遇到了相同的问题，删除原文件，具体是指哪个文件？可否详细说一下~谢谢~
