### ISSUE TITLE
EasyDarwin-Linux-x86_64-v7.3.17.1114在centos7下无法登陆

### ISSUE THREAD

**Issue by zphj1987** [EasyDarwin/EasyDarwin#88]
运行后无法登陆
OS版本：CentOS Linux release 7.4.1708 (Core)
访问正常 http://192.168.219.128:10080/api
![image](https://user-images.githubusercontent.com/2322061/37197014-f8d9c6dc-23b3-11e8-89b0-dcbb918b5d1d.png)
登陆界面也有

就是无法登陆
http://192.168.219.128:10080/api/v1/login?username=admin&password=21232f297a57a5a743894a0e4a801fc3
显示如下：
{
   "EasyDarwin" : {
      "Body" : {
         "Token" : "EasyDarwinTempToken"
      },
      "Header" : {
         "CSeq" : "1",
         "ErrorNum" : "200",
         "ErrorString" : "Success OK",
         "MessageType" : "MSG_SC_SERVER_LOGIN_ACK",
         "Version" : "v1"
      }
   }
}

**Comment by zphj1987** [comment]
root@ubuntu-virtual-machine:~/EasyDarwin-Linux-x86_64-v7.3.17.1114/EasyDarwin# WARNING: No module folder exists.
INFO: Loading Module...QTSSReflectorModule [static]
INFO: Loading Module...QTSSAccessLogModule [static]
INFO: Loading Module...QTSSFlowControlModule [static]
INFO: Loading Module...QTSSPosixFileSysModule [static]
INFO: Loading Module...QTSSAccessModule [static]
Streaming Server done starting up
INFO: HTTPSession offline from ip[127.0.0.1]

**Comment by wantstudy** [comment]
我下载的项目里没有nginx目录啊，   那怎么访问登陆页面啊，
访问其他的连接都返回json数据

**Comment by LinChengChun** [comment]
请问你的 EasyDarwin 是什么版本？

**Comment by wantstudy** [comment]
下面是我的api/v1/getserverinfo 接口返回的数据，我应该是下的最新的源码包安装的


{
"EasyDarwin": {
"Body": {
"Hardware": "x86",
"InterfaceVersion": "v1",
"RunningTime": "0 Days 0 Hours 21 Mins 32 Secs",
"Server": "Server: EasyDarwin/7.3 (Build/17.1114; Platform/Linux; Release/EasyDarwin; State/Development; )"
},
"Header": {
"CSeq": "1",
"ErrorNum": "200",
"ErrorString": "Success OK",
"MessageType": "MSG_SC_SERVER_INFO_ACK",
"Version": "v1"
}
}
}

**Comment by wantstudy** [comment]
7,.2.17.0308.tar.gz

https://github.com/EasyDarwin/EasyDarwin/archive/v7.2.17.0308.tar.gz

**Comment by wantstudy** [comment]
看错了，我直接下的是主分支上的

wget https://github.com/EasyDarwin/EasyDarwin/archive/master.zip

**Comment by wantstudy** [comment]
我下了另一个版本，找到nginx目录了，谢谢

**Comment by zphj1987** [comment]
标题上写了版本  
EasyDarwin-Linux-x86_64-v7.3.17.1114

**Comment by susu3621** [comment]
ubuntu 16.04上也无法登录，同样api/v1/getserverinfo接口和login接口api/v1/login?username=admin&password=21232f297a57a5a743894a0e4a801fc3，都工作正常。
同版本的Windows程序，可以运行登录。

**Comment by babosa** [comment]
用最新的8.x版本
