### ISSUE TITLE
使用EasyPusher自带的DEMO推视频流，直播的时候一直花屏

### ISSUE THREAD

**Issue by zjy28** [EasyDarwin/EasyDarwin#9]
服务器程序一直输出
==============>Find Not Continued Seq[qd]==[qd]
GetNewestKeyFrameFirstPcket -->[NotFound]

**Comment by xiejiashu** [comment]
这个跟EasyPusher推送没有关系，主要是服务器在转发的时候，第一帧转发给客户端的没有强制现在发送sps/pps+I帧，导致一开始来的就是一些非关键帧，所以就花屏了

**Comment by xiejiashu** [comment]
新版本已经做了关键帧过滤，请帮忙看看效果
