### ISSUE TITLE
推拉流怎么配置

### ISSUE THREAD

**Issue by wblbird** [EasyDarwin/EasyDarwin#90]
想在局域网搭建流媒体测试直播。
下载了EasyDarwin，启动start.bat
提示：
EasyDarwin rtsp server listening on rtsp://192.168.0.103:554 in production mode
EasyDarwin http server listening on http://192.168.0.103:10008 in production mode
然后访问了http://192.168.0.103:10008，没有推拉流
然后下载了EasyScreenLive，进行桌面直播推流，
EasyScreenLive里的推流地址：开启RTMP推送: rtmp://192.168.0.103:10085/live/easy-dln
然后去刷新http://192.168.0.103:10008，并没有推拉流，这个怎么弄呢？

用EasyScreenLive倒是能直接开启RTSP服务，能用easyplay直接播放

**Comment by lifeibin** [comment]
EasyDarwin是一个RTSP流媒体服务器，只能接收转发rtsp流，这种rtmp流EasyDarwin 是无法处理的

**Comment by Derek52722** [comment]
那rtsp流怎么配置呢。启动demo项目，推流列表里都无法配置的。
另外，请问项目是否支持 带认证的rtsp流拉取呢？就是直接对接摄像头的那种。

**Comment by feichaohao** [comment]
同问

**Comment by Tangyun715** [comment]
拉流列表怎么配置？

**Comment by penggy** [comment]
RTSP 推流工具有很多啊, 比如README里介绍的ffmpeg推法, 比如Easy系列的EasyPusher
