### ISSUE TITLE
Connecting two Easy Darwin servers

### ISSUE THREAD

**Issue by sleebapaul** [EasyDarwin/EasyDarwin#93]
In the README, the explanation is to use `FFMPEG` for generating the `rtsp` stream to Easy Darwin server. Then the stream is available at `rtsp://localhost/test`. What about restreaming this stream. That is again to an Easy Darwin server. Do we need to use the `FFMPEG` again? Or there is any way to pluck out `FFMPEG` from the pipeline this time?

**Comment by penggy** [comment]
If you restreaming on /test, EasyDarwin will response 406, Not Accept, [here the code](https://github.com/EasyDarwin/EasyDarwin/blob/4a9facfd94e1fac59ec755ad149f839dab74abe7/rtsp-session.js#L259)

**Comment by sleebapaul** [comment]
Is there any chance to build up a proxy rtsp server using Easy Darwin?

**Comment by penggy** [comment]
This is a planing feature, redirect push rtsp stream to another rtsp server node. BTW, fetch stream from another rtsp stream to this EasyDarwin server node will comming soon.

**Comment by afshin-hoseini** [comment]
@penggy Any updates on this feature?

**Comment by milkywayriver** [comment]
already added.
we call it pull to push.
The server can pull stream from a rtsp source and push to another clients.

**Comment by milkywayriver** [comment]
This feature was added on the GO version, which in the master branch
