### ISSUE TITLE
[FAQ] RTSP Server Side Record and Playback

### ISSUE THREAD

**Issue by kirantpatil** [EasyDarwin/EasyDarwin#98]
Greetings EasyDarwin community!

Does it support, RTSP Server Side Record and Playback ?

Thanks.

**Comment by kirantpatil** [comment]
Dear @babosa, please help me to test Record and Playback feature from server.

Thanks.

**Comment by kirantpatil** [comment]
Please, help us to implement it and we would like to contribute it back to community.

Thanks.

**Comment by kirantpatil** [comment]
Also, we would like to store the recorded videos specific to user account by using any cloud storage like google/amazon ...

**Comment by kirantpatil** [comment]
Closing this since it is in progress as per https://github.com/EasyDarwin/EasyDarwin/issues/105

**Comment by milkywayriver** [comment]
the go version can record stream to m3u8 stream via ffmpeg
